name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, rc ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #TODO add 9.2.1 back once sweph 1.4.1.0 is out
        #ghc: ['8.8.4', '8.10.4', '9.0.1', '9.2.1']
        ghc: ['8.8.4', '8.10.4', '9.0.1']
        cabal: ['3.2']
        os: [ubuntu-latest, macos-latest]
    env:
      CONFIG: "--enable-tests --enable-benchmarks --test-show-details=streaming"
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal v2-update
      - run: cabal v2-freeze $CONFIG
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal v2-build $CONFIG
      - run: cabal v2-test $CONFIG

