name: "Build and Release to Heroku"
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-21.11
    - name: Login to Heroku Container Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run:
        heroku container:login
    - name: Build with nix and load into docker 
      run: 
        docker load < $(nix-build ./nix/docker.nix)
    - name: Push to container Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        docker tag postgres-explain-visualizer:latest registry.heroku.com/pgexplain/web
        docker push registry.heroku.com/pgexplain/web
    - name:  Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run:
        heroku container:release web -a pgexplain
